---
- name: Install epel
  command: "{{ item }}"
  with_items:
  - "{{ update }}"
  - "{{ epel }}"
- name: Install Nagios Plugins
  package:
    name: "{{ package_plugin }}"
    state: latest
  notify:
  - Start/Enable nrpe
  - Restart nrpe