---
- name: Install http Package
  hosts: all
  become: yes
  tasks:
    - name: Install HTTP
      package:
        name: "{{ apache_package }}"
        state: latest

    # - name: Start & Enable service httpd
    #   service:
    #     name: "{{ apache_service }}"
    #     state: started
    #     enabled: yes


    ---
- name: URL Nagios Plugin
  get_url:
    url: "{{ nagios_plugin_url }}"
    dest: "/home/{{ vm_user }}" 